config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :blogs do
    post :confirm, on: :collection
    resources :comments
  end

  resources :contacts,only:[:new,:create] do
    collection do
      post :confirm
    end
  end

  root 'top#index'

  resources :poems,only:[:index,:show]

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only:[:index,:show]
  resources :relationships, only:[:create,:destroy]
  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :blog
  has_many :notifications, dependent: :destroy

  # pusherでコメント作成のトリガを作成する
  def self.notify_cmt_creation(comment,current_user)
    unless comment.blog.user_id == current_user.id
      Pusher.trigger("user_#{comment.blog.user_id}_channel","comment_created",{
        message: "あなたの作成したブログにコメントが付きました"
      })
    end
    Pusher.trigger("user_#{comment.blog.user_id}_channel", 'notification_created', {
      unread_counts: Notification.where(user_id: comment.blog.user.id, read: false).count
    })
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment_and_blog, only:[:edit,:destroy,:update]

  def create
    @comment = current_user.comments.build(comment_params)
    @blog = @comment.blog
    @notification = @comment.notifications.build(user_id: @blog.user.id)
    respond_to do |format|
      if @comment.save
        # format.html {redirect_to blog_path(@blog), notice: "コメントを投稿しました。"}
        format.js {render :index}
        Comment.notify_cmt_creation(@comment,current_user)
      else
        format.html {render :new}
      end
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to blog_path(@blog), notice: "ブログを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    respond_to do |format|
      @comment.destroy
      format.html {redirect_to blog_path(@blog), notice: "コメントを削除しました。"}
      format.js {render :index}
    end
  end

  private
  def comment_params
      params.require(:comment).permit(:blog_id,:content)
  end

  def set_comment_and_blog
    @comment = Comment.find(params[:id])
    @blog = @comment.blog
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([blog,comment], remote: true ) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= comment.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :blog_id %>
  <div class="field">
    <%= f.text_field :content, placeholder: "内容", class: "form-control"  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <li>
        <p class="left"><%= comment.user.name %>さんがコメントしました。</p>
        <p class="left"><%= comment.content %></p>
        <% if current_user.id == comment.user.id %>
          <p class="right">
            <%= link_to '', edit_blog_comment_path(blog, comment), class: "fa fa-pencil-square-o fa-lg" %>
            <%= link_to '', blog_comment_path(blog, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
          </p>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <p id="notice"><%= notice %></p>
    <% if @comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= comment.errors.count %>件のエラーがあります。</h2>

        <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_for([@blog, @comment]) do |f| %>
      <h2>コメントを編集する</h2>
      <%= f.hidden_field :blog_id %>
      <div class="field">
        <%= f.text_field :content, placeholder: "内容", class: "form-control"  %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.blog.comments, blog: @comment.blog }) %>")
$(':text').val('')